/*
 * This source file was generated by the Gradle 'init' task
 */
package bowling_kata;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class AppTest {
    @Test
    void appHasAGreeting() {
        App classUnderTest = new App();

        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

}
